// <auto-generated />
using System;
using BackendData.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230203015544_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("BackendData.DomainModel.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "IJmuiden",
                            Country = "Netherlands",
                            HouseNumber = 11,
                            Street = "Plain1945",
                            ZipCode = "1971GL"
                        },
                        new
                        {
                            Id = 2,
                            City = "Haarlem",
                            Country = "Netherlands",
                            HouseNumber = 12,
                            Street = "Hendrik Figeeweg",
                            ZipCode = "2031BJ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
